# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hdotpolycpp <- function(xy, traps, Tsk, markocc, cumk, detectfn, gsb, convex, dim, grain, ncores) {
    .Call(`_secrfunc_hdotpolycpp`, xy, traps, Tsk, markocc, cumk, detectfn, gsb, convex, dim, grain, ncores)
}

makegkPolygoncpp <- function(detectfn, dim, convex, grain, ncores, gsbval, cumk, traps, mask) {
    .Call(`_secrfunc_makegkPolygoncpp`, detectfn, dim, convex, grain, ncores, gsbval, cumk, traps, mask)
}

polygonhistoriescpp <- function(nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, debug) {
    .Call(`_secrfunc_polygonhistoriescpp`, nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, debug)
}

polygonhistories2cpp <- function(nc, detectfn, grain, ncores, safeLL, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, mask_indices, mask_offsets, mask_id, debug) {
    .Call(`_secrfunc_polygonhistories2cpp`, nc, detectfn, grain, ncores, safeLL, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex, mask_indices, mask_offsets, mask_id, debug)
}

polygonfxicpp <- function(nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex) {
    .Call(`_secrfunc_polygonfxicpp`, nc, detectfn, grain, ncores, minp, binomN, w, xy, start, group, hk, H, gsbval, pID, mask, density, PIA, Tsk, h, hindex)
}

